// Generated by gencpp from file argos_bridge/MotoGroundList.msg
// DO NOT EDIT!


#ifndef ARGOS_BRIDGE_MESSAGE_MOTOGROUNDLIST_H
#define ARGOS_BRIDGE_MESSAGE_MOTOGROUNDLIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <argos_bridge/MotoGround.h>

namespace argos_bridge
{
template <class ContainerAllocator>
struct MotoGroundList_
{
  typedef MotoGroundList_<ContainerAllocator> Type;

  MotoGroundList_()
    : n(0)
    , motoGrounds()  {
    }
  MotoGroundList_(const ContainerAllocator& _alloc)
    : n(0)
    , motoGrounds(_alloc)  {
  (void)_alloc;
    }



   typedef uint32_t _n_type;
  _n_type n;

   typedef std::vector< ::argos_bridge::MotoGround_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::argos_bridge::MotoGround_<ContainerAllocator> >::other >  _motoGrounds_type;
  _motoGrounds_type motoGrounds;





  typedef boost::shared_ptr< ::argos_bridge::MotoGroundList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::argos_bridge::MotoGroundList_<ContainerAllocator> const> ConstPtr;

}; // struct MotoGroundList_

typedef ::argos_bridge::MotoGroundList_<std::allocator<void> > MotoGroundList;

typedef boost::shared_ptr< ::argos_bridge::MotoGroundList > MotoGroundListPtr;
typedef boost::shared_ptr< ::argos_bridge::MotoGroundList const> MotoGroundListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::argos_bridge::MotoGroundList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::argos_bridge::MotoGroundList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::argos_bridge::MotoGroundList_<ContainerAllocator1> & lhs, const ::argos_bridge::MotoGroundList_<ContainerAllocator2> & rhs)
{
  return lhs.n == rhs.n &&
    lhs.motoGrounds == rhs.motoGrounds;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::argos_bridge::MotoGroundList_<ContainerAllocator1> & lhs, const ::argos_bridge::MotoGroundList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace argos_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::argos_bridge::MotoGroundList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::argos_bridge::MotoGroundList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::argos_bridge::MotoGroundList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::argos_bridge::MotoGroundList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::argos_bridge::MotoGroundList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::argos_bridge::MotoGroundList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::argos_bridge::MotoGroundList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "49d994c0a5d5dc1356fd2c48d2b519a1";
  }

  static const char* value(const ::argos_bridge::MotoGroundList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x49d994c0a5d5dc13ULL;
  static const uint64_t static_value2 = 0x56fd2c48d2b519a1ULL;
};

template<class ContainerAllocator>
struct DataType< ::argos_bridge::MotoGroundList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "argos_bridge/MotoGroundList";
  }

  static const char* value(const ::argos_bridge::MotoGroundList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::argos_bridge::MotoGroundList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 n\n"
"MotoGround[] motoGrounds\n"
"\n"
"================================================================================\n"
"MSG: argos_bridge/MotoGround\n"
"float32 value\n"
"float32 offset_x\n"
"float32 offset_y\n"
;
  }

  static const char* value(const ::argos_bridge::MotoGroundList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::argos_bridge::MotoGroundList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.n);
      stream.next(m.motoGrounds);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotoGroundList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::argos_bridge::MotoGroundList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::argos_bridge::MotoGroundList_<ContainerAllocator>& v)
  {
    s << indent << "n: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.n);
    s << indent << "motoGrounds[]" << std::endl;
    for (size_t i = 0; i < v.motoGrounds.size(); ++i)
    {
      s << indent << "  motoGrounds[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::argos_bridge::MotoGround_<ContainerAllocator> >::stream(s, indent + "    ", v.motoGrounds[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARGOS_BRIDGE_MESSAGE_MOTOGROUNDLIST_H
