// Generated by gencpp from file argos_bridge/Puck.msg
// DO NOT EDIT!


#ifndef ARGOS_BRIDGE_MESSAGE_PUCK_H
#define ARGOS_BRIDGE_MESSAGE_PUCK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/ColorRGBA.h>

namespace argos_bridge
{
template <class ContainerAllocator>
struct Puck_
{
  typedef Puck_<ContainerAllocator> Type;

  Puck_()
    : color()
    , range(0.0)
    , angle(0.0)  {
    }
  Puck_(const ContainerAllocator& _alloc)
    : color(_alloc)
    , range(0.0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::ColorRGBA_<ContainerAllocator>  _color_type;
  _color_type color;

   typedef float _range_type;
  _range_type range;

   typedef float _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::argos_bridge::Puck_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::argos_bridge::Puck_<ContainerAllocator> const> ConstPtr;

}; // struct Puck_

typedef ::argos_bridge::Puck_<std::allocator<void> > Puck;

typedef boost::shared_ptr< ::argos_bridge::Puck > PuckPtr;
typedef boost::shared_ptr< ::argos_bridge::Puck const> PuckConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::argos_bridge::Puck_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::argos_bridge::Puck_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::argos_bridge::Puck_<ContainerAllocator1> & lhs, const ::argos_bridge::Puck_<ContainerAllocator2> & rhs)
{
  return lhs.color == rhs.color &&
    lhs.range == rhs.range &&
    lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::argos_bridge::Puck_<ContainerAllocator1> & lhs, const ::argos_bridge::Puck_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace argos_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::argos_bridge::Puck_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::argos_bridge::Puck_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::argos_bridge::Puck_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::argos_bridge::Puck_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::argos_bridge::Puck_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::argos_bridge::Puck_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::argos_bridge::Puck_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4ed42de6679ef0abec7e884aca1135c6";
  }

  static const char* value(const ::argos_bridge::Puck_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4ed42de6679ef0abULL;
  static const uint64_t static_value2 = 0xec7e884aca1135c6ULL;
};

template<class ContainerAllocator>
struct DataType< ::argos_bridge::Puck_<ContainerAllocator> >
{
  static const char* value()
  {
    return "argos_bridge/Puck";
  }

  static const char* value(const ::argos_bridge::Puck_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::argos_bridge::Puck_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/ColorRGBA color\n"
"float32 range\n"
"float32 angle\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/ColorRGBA\n"
"float32 r\n"
"float32 g\n"
"float32 b\n"
"float32 a\n"
;
  }

  static const char* value(const ::argos_bridge::Puck_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::argos_bridge::Puck_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.color);
      stream.next(m.range);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Puck_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::argos_bridge::Puck_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::argos_bridge::Puck_<ContainerAllocator>& v)
  {
    s << indent << "color: ";
    s << std::endl;
    Printer< ::std_msgs::ColorRGBA_<ContainerAllocator> >::stream(s, indent + "  ", v.color);
    s << indent << "range: ";
    Printer<float>::stream(s, indent + "  ", v.range);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARGOS_BRIDGE_MESSAGE_PUCK_H
