# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from argos_bridge/BaseGroundList.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import argos_bridge.msg

class BaseGroundList(genpy.Message):
  _md5sum = "69c1c089ae74b076579a8bd75e220110"
  _type = "argos_bridge/BaseGroundList"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint32 n
BaseGround[] baseGrounds

================================================================================
MSG: argos_bridge/BaseGround
float32 value
float32 offset_x
float32 offset_y
"""
  __slots__ = ['n','baseGrounds']
  _slot_types = ['uint32','argos_bridge/BaseGround[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       n,baseGrounds

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(BaseGroundList, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.n is None:
        self.n = 0
      if self.baseGrounds is None:
        self.baseGrounds = []
    else:
      self.n = 0
      self.baseGrounds = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.n
      buff.write(_get_struct_I().pack(_x))
      length = len(self.baseGrounds)
      buff.write(_struct_I.pack(length))
      for val1 in self.baseGrounds:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.value, _x.offset_x, _x.offset_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.baseGrounds is None:
        self.baseGrounds = None
      end = 0
      start = end
      end += 4
      (self.n,) = _get_struct_I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.baseGrounds = []
      for i in range(0, length):
        val1 = argos_bridge.msg.BaseGround()
        _x = val1
        start = end
        end += 12
        (_x.value, _x.offset_x, _x.offset_y,) = _get_struct_3f().unpack(str[start:end])
        self.baseGrounds.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.n
      buff.write(_get_struct_I().pack(_x))
      length = len(self.baseGrounds)
      buff.write(_struct_I.pack(length))
      for val1 in self.baseGrounds:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.value, _x.offset_x, _x.offset_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.baseGrounds is None:
        self.baseGrounds = None
      end = 0
      start = end
      end += 4
      (self.n,) = _get_struct_I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.baseGrounds = []
      for i in range(0, length):
        val1 = argos_bridge.msg.BaseGround()
        _x = val1
        start = end
        end += 12
        (_x.value, _x.offset_x, _x.offset_y,) = _get_struct_3f().unpack(str[start:end])
        self.baseGrounds.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
