# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from argos_bridge/LedsColor.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class LedsColor(genpy.Message):
  _md5sum = "62998bbed77dd665705d07b81ccc0148"
  _type = "argos_bridge/LedsColor"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """std_msgs/ColorRGBA color
uint32 led_number
uint8 intensity

================================================================================
MSG: std_msgs/ColorRGBA
float32 r
float32 g
float32 b
float32 a
"""
  __slots__ = ['color','led_number','intensity']
  _slot_types = ['std_msgs/ColorRGBA','uint32','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       color,led_number,intensity

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LedsColor, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.color is None:
        self.color = std_msgs.msg.ColorRGBA()
      if self.led_number is None:
        self.led_number = 0
      if self.intensity is None:
        self.intensity = 0
    else:
      self.color = std_msgs.msg.ColorRGBA()
      self.led_number = 0
      self.intensity = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4fIB().pack(_x.color.r, _x.color.g, _x.color.b, _x.color.a, _x.led_number, _x.intensity))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.color is None:
        self.color = std_msgs.msg.ColorRGBA()
      end = 0
      _x = self
      start = end
      end += 21
      (_x.color.r, _x.color.g, _x.color.b, _x.color.a, _x.led_number, _x.intensity,) = _get_struct_4fIB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4fIB().pack(_x.color.r, _x.color.g, _x.color.b, _x.color.a, _x.led_number, _x.intensity))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.color is None:
        self.color = std_msgs.msg.ColorRGBA()
      end = 0
      _x = self
      start = end
      end += 21
      (_x.color.r, _x.color.g, _x.color.b, _x.color.a, _x.led_number, _x.intensity,) = _get_struct_4fIB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4fIB = None
def _get_struct_4fIB():
    global _struct_4fIB
    if _struct_4fIB is None:
        _struct_4fIB = struct.Struct("<4fIB")
    return _struct_4fIB
